### ISSUE TITLE
Provide an aiohttp-less version for server

### ISSUE THREAD

**Issue by gaborbernat** [devpi/devpi#998]
https://github.com/aio-libs/aiohttp is very slow at adding new Python version support - so allow not using it. Already raised this https://github.com/devpi/devpi/issues/918 but got closed. Because aiohttp waits until 3.12 final and even then needs a few days/weeks to get a new release devpi is acting as a gatekeeper to test early any packages that depend on devpi (such as tox). This also makes so that one cannot upgrade to 3.12 on day 1 when running locally devpi.

**Comment by fschulze** [comment]
Can you suggest an alternative async http library?

**Comment by gaborbernat** [comment]
https://www.python-httpx.org/async/ is great 👍

**Comment by fschulze** [comment]
Doesn’t seem to have a 3.12 compatible release either yet.

**Comment by gaborbernat** [comment]
Doesn't need it, it's an universal wheel `httpx-0.25.0-py3-none-any.whl` 👍

**Comment by fschulze** [comment]
I'm also thinking about ditching async completely and using [``concurrent.futures``](https://docs.python.org/3/library/concurrent.futures.html) with a thread pool instead. For our use-case that might make more sense.

**Comment by gaborbernat** [comment]
Either works for me 😊

**Comment by gaborbernat** [comment]
@fschulze Any progress on this, aiohttp still doesn't support 3.12 and by extension devpi neither 😢

**Comment by fschulze** [comment]
Seems to work with ``aiohttp==3.9.0b0`` at least: https://github.com/devpi/devpi/actions/runs/6608310136/job/17946969395

For me this has no high priority. It is likely that I will look into ``concurrent.futures`` soon, but there is no ETA at all. Most users and customers I know only update Python when the version they are using isn't supported anymore. Also devpi-web is currently blocked by the Chameleon template library being broken on Python 3.12, even though it is pure Python, but deprecations got to it.

It looks like tox tests are running on 3.12 though: https://github.com/tox-dev/tox/actions/runs/6624163180/job/18007221072, are you skipping the test that used devpi-server or marked it xfail? I don't see anything related, but devpi-server is in the list of installed packages.

**Comment by gaborbernat** [comment]
devpi server is still unusable for me with:

```
Fatal error from pip prevented installation. Full pip output in file:
    /Users/bgabor8/.local/pipx/logs/cmd_2023-10-30_14.10.43_pip_errors.log

pip failed to build package:
    aiohttp

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    aiohttp/_websocket.c:3042:55: error: no member named 'ob_digit' in 'struct _longobject'
    aiohttp/_websocket.c:3097:55: error: no member named 'ob_digit' in 'struct _longobject'
    aiohttp/_websocket.c:3238:55: error: no member named 'ob_digit' in 'struct _longobject'
    aiohttp/_websocket.c:3293:55: error: no member named 'ob_digit' in 'struct _longobject'
    aiohttp/_websocket.c:3744:47: error: no member named 'ob_digit' in 'struct _longobject'
    error: command '/usr/bin/clang' failed with exit code 1

Error installing devpi-server.
```

So I can open an issue to support 3.12 if you want....

**Comment by gaborbernat** [comment]
Welp, this is stoping me doing tox development 🤦

**Comment by fschulze** [comment]
Did you try [the workaround I suggested a year ago](https://github.com/tox-dev/tox/pull/2466#issuecomment-1221838480)?

**Comment by gaborbernat** [comment]
I'm using it via devpi  process that doesn't allow that awkward workaround 🤷‍♂️

**Comment by fschulze** [comment]
As far as I can tell devpi-process doesn't install any packages itself, so it relies on the test setup it is used in, which you control.

**Comment by gaborbernat** [comment]
Would it be possible to get a new release? I'm still unable to install and use this tool on 3.12 via pipx.
