### ISSUE TITLE
server-6.12.0 fails to start

### ISSUE THREAD

**Issue by plinss** [devpi/devpi#1043]
After upgrading to 6.12.0, devpi-server fails to start with the following traceback:

```
Traceback (most recent call last):
  File "/app/devpi/venv/bin/devpi-server", line 5, in <module>
    from devpi_server.main import main
  File "/app/devpi/venv/lib/python3.10/site-packages/devpi_server/main.py", line 30, in <module>
    from .views import apireturn
  File "/app/devpi/venv/lib/python3.10/site-packages/devpi_server/views.py", line 423, in <module>
    class ToxResultHandling:
  File "/app/devpi/venv/lib/python3.10/site-packages/devpi_server/views.py", line 424, in ToxResultHandling
    _block: bool = attrs.field(default=False, alias="_block")
TypeError: field() got an unexpected keyword argument 'alias'
```

Manually upgrading the `attrs` package to the latest version resolves the issue. It looks like perhaps you forgot to update the dependency version?

**Comment by fschulze** [comment]
Thanks for the report. I didn't realize I was using a feature added at the end of 2022 and the version minimum was outdated. I generally try to update all dependencies when I upgrade installations, so it didn't come up for me. I updated the pin, but will not make a new release just for it.
